/** Declaration file generated by dts-gen */

export function change(mode: any, strict: any): void;

export function get(path: any, callback: any): any;

export function getSync(path: any): any;

export function set(path: any, attrs: any, callback: any): any;

export function setSync(path: any, attrs: any): any;

export namespace change {
    const prototype: {
    };

}

export namespace get {
    const prototype: {
    };

}

export namespace getSync {
    const prototype: {
    };

}

export namespace set {
    const prototype: {
    };

}

export namespace setSync {
    const prototype: {
    };

}

